Core concepts additions
LIT-Protocol/docs pull request #123
Opened 2023-08-24 20:09 UTC by a1ttech

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Introducing new feature (non-breaking change which adds functionality)

Link to the relevant updated sections in the Netlify preview

- [ ] Link 1: 'core concepts' section (all entries)

# Checklist:

General
- [ ] I have performed a self-review of my code
- [ ] I have fixed all grammar issues (can use an AI tool to check), and explanations are in active voice
- [ ] I have checked the additions are concise
- [ ] Language is consistent with existing documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published (ie. SDK changes, node dependencies)

If I have added a new concept, I have
- [ ] included a beginner friendly explanation
- [ ] included a basic technical introduction and code sample
- [ ] new terms are defined, both in relevant new pages and in the glossary

2023-08-25 23:13 UTC, debbly requested changes
Hey - for the new core concepts, they should only be included in the V3 docs and this PR should only be for V3 docs updates. Was expecting just the core concept pages for V3 ...

I'm unsure what's going on with the naming scheme under version 2, there shouldn't be any ___2.md docs since we don't need to add in the 2 delineated for files.

2023-09-01 19:24 UTC, a1ttech commented
> Hey - for the new core concepts, they should only be included in the V3 docs and this PR should only be for V3 docs updates. Was expecting just the core concept pages for V3 ...
> 
> I'm unsure what's going on with the naming scheme under version 2, there shouldn't be any ___2.md docs since we don't need to add in the 2 delineated for files.

Yea this is really strange. I'm not sure what happened, as i didn't touch the V2 docs at all? Everything I pushed was under the /docs section (V3) so I don't know where all the V2 changes came from

2023-09-11 21:38 UTC, debbly commented
One thing you can do is to re-open a PR with just [this commit](https://github.com/LIT-Protocol/docs/pull/123/commits/3912947b84dc532ab050e786e9c698881d662f97), since likely you ran into issues with versioning and the files were created and added

2023-09-12 19:56 UTC, debbly commented on docs/concepts/access-control-concept.md
> +Lit Protocol provides developers with a decentralized access control layer that can be used to [encrypt](/v3/sdk/access-control/encryption#technical-walkthrough) content for private and permissioned
the links should be relative, and should not include the version!

For example: `../sdk/access-control/encryption#technical-walkthrough`

2023-09-12 20:01 UTC, debbly commented on docs/concepts/access-control-concept.md
> +Lit Protocol provides developers with a decentralized access control layer that can be used to [encrypt](/v3/sdk/access-control/encryption#technical-walkthrough) content for private and permissioned
best practice from docusaurus here: https://docusaurus.io/docs/versioning#link-docs-by-file-paths

2023-09-13 19:43 UTC, debbly approved these changes

2023-09-13 19:44 UTC, merged