remove recaptcha, add more session signature info
LIT-Protocol/docs pull request #151
Opened 2023-10-16 16:18 UTC by joshLong145

# Description
- Removes stale documentation for `otp` authentication on sdk v2 where repatcha implementations are outlined which where not merged into the sdk. if we wish to add it back at another point in time we can add the documentation back to this page.

- Adds more context to session signature signing examples for `OTP` auth method

2023-10-16 16:21 UTC, sarahzdev reviewed
be sure to update the same pages in `versioned_docs/version-2.0` folder

2023-10-17 00:13 UTC, debbly requested changes

2023-10-17 00:13 UTC, debbly commented on docs/sdk/authentication/session-sigs/auth-methods/email-sms.md
> +you can use the `session.fetchPKPThroughRelayer`  method above to query pkp public keys associated with a given auth method. you can also use the `contracts-sdk` to query pkp information by Authentic
```suggestion
The `session.fetchPKPThroughRelayer`  method above can be used to query PKP public keys associated with a given auth method. You can also use the `contracts-sdk` to query PKP information by Authentication Method.
```

2023-10-17 00:13 UTC, debbly commented on versioned_docs/version-2.0/sdk/explanation/authentication/sessionSigs/authMethods/email-sms.md
> +The example will assume you are using `LitNodeClient` but this example also works with `LitNodeClientNodeJS`
```suggestion
The example assumes you are using `LitNodeClient` and also works with `LitNodeClientNodeJS`
```

2023-10-17 00:13 UTC, debbly commented on versioned_docs/version-2.0/sdk/explanation/authentication/sessionSigs/authMethods/email-sms.md
> +Request a specified pkp to sign a session signature, authenticating with an `Auth Method` for a given `PKP`
```suggestion
Request a specified PKP to sign a session signature, authenticating with an `Auth Method` for a given `PKP`
```

2023-10-17 00:13 UTC, debbly commented on versioned_docs/version-2.0/sdk/explanation/authentication/sessionSigs/authMethods/email-sms.md
> +you can use the `session.fetchPKPThroughRelayer`  method above to query pkp public keys associated with a given auth method. you can also use the `contracts-sdk` to query pkp information by Authentic
```suggestion
The `session.fetchPKPThroughRelayer`  method above can be used to query PKP public keys associated with a given auth method. You can also use the `contracts-sdk` to query PKP information by Authentication Method.
```

2023-10-17 00:57 UTC, sarahzdev approved these changes

2023-10-23 21:44 UTC, debbly approved these changes

2023-10-23 21:44 UTC, merged